name: ExaminingEV19-Env
channels:
 - conda-forge
dependencies:
 - python>=3.5
 - matplotlib>=2.0
 - numpy
 - ipywidgets
 - ipympl
 - widgetsnbextension
 - jupyter_contrib_nbextensions
 - pandas
 - scipy
 - scikit-learn
 - scikit-image
 - pillow
 - tornado<6